# -*- coding: utf-8 -*-
import re
verses = [
("Jeremiah 29:11","For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future."),
("Philippians 4:13","I can do all things through Christ who strengthens me."),
("Psalm 23:1","The Lord is my shepherd; I shall not want."),
("Proverbs 3:5-6","Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight."),
("John 3:16","For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life."),
("Joshua 1:9","Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go."),
("Romans 8:28","We know that in all things God works for the good of those who love him, who have been called according to his purpose."),
("Philippians 4:6","Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God."),
("Numbers 6:24-25","The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you."),
("Matthew 11:28","Come to me, all you who are weary and burdened, and I will give you rest."),
("Psalm 147:3","He heals the brokenhearted and binds up their wounds."),
("Psalm 107:1","Give thanks to the Lord, for he is good; his love endures forever."),
("Matthew 5:16","Let your light shine before others, that they may see your good deeds and glorify your Father in heaven."),
("Isaiah 40:31","Those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint."),
("1 Corinthians 13:4","Love is patient, love is kind. It does not envy, it does not boast, it is not proud."),
("Lamentations 3:22-23","The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning."),
("Matthew 19:26","With man this is impossible, but with God all things are possible."),
("Zephaniah 3:17","The Lord your God is with you, the Mighty Warrior who saves. He will take great delight in you."),
("1 Peter 5:7","Cast all your anxiety on him because he cares for you."),
("Psalm 37:4","Delight yourself in the Lord, and he will give you the desires of your heart."),
("2 Chronicles 7:14","If my people, who are called by my name, will humble themselves and pray and seek my face, then I will hear from heaven."),
("Proverbs 9:10","The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding."),
("John 14:6","I am the way and the truth and the life. No one comes to the Father except through me."),
("Zechariah 4:6","Not by might nor by power, but by my Spirit, says the Lord Almighty."),
("Romans 5:8","But God demonstrates his own love for us in this: While we were still sinners, Christ died for us."),
("Psalm 46:1","God is our refuge and strength, an ever-present help in trouble."),
("Isaiah 41:10","So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you."),
("John 13:34","A new command I give you: Love one another. As I have loved you, so you must love one another."),
("Romans 12:2","Do not conform to the pattern of this world, but be transformed by the renewing of your mind."),
("Psalm 119:105","Your word is a lamp for my feet, a light on my path."),
("Ephesians 2:8-9","For it is by grace you have been saved, through faith - and this is not from yourselves, it is the gift of God."),
("Philippians 4:19","My God will meet all your needs according to the riches of his glory in Christ Jesus."),
("John 10:10","I have come that they may have life, and have it to the full."),
("1 John 4:19","We love because he first loved us."),
("Proverbs 4:23","Above all else, guard your heart, for everything you do flows from it."),
("Colossians 3:23","Whatever you do, work at it with all your heart, as working for the Lord, not for human masters."),
("Proverbs 22:6","Start children off on the way they should go, and even when they are old they will not turn from it."),
("Isaiah 26:3","You will keep in perfect peace those whose minds are steadfast, because they trust in you."),
("John 14:27","Peace I leave with you; my peace I give you. Do not let your hearts be troubled and do not be afraid."),
("Micah 6:8","He has shown you what is good. And what does the Lord require of you? To act justly and to love mercy and to walk humbly with your God."),
("Galatians 6:9","Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up."),
("Romans 15:13","May the God of hope fill you with all joy and peace as you trust in him."),
("Proverbs 16:3","Commit to the Lord whatever you do, and he will establish your plans."),
("Psalm 121:1-2","I lift up my eyes to the mountains - where does my help come from? My help comes from the Lord, the Maker of heaven and earth."),
("Revelation 21:4","He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain."),
("John 8:12","I am the light of the world. Whoever follows me will never walk in darkness, but will have the light of life."),
("Ephesians 3:20","Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us."),
("2 Corinthians 5:17","If anyone is in Christ, the new creation has come: The old has gone, the new is here!"),
("Romans 8:38-39","Neither death nor life, nor angels nor demons, neither the present nor the future, will be able to separate us from the love of God."),
("Matthew 7:7","Ask and it will be given to you; seek and you will find; knock and the door will be opened to you."),
("Deuteronomy 31:6","Be strong and courageous. Do not be afraid or terrified, for the Lord your God goes with you."),
("Isaiah 43:2","When you pass through the waters, I will be with you; and when you pass through the rivers, they will not sweep over you."),
("James 4:8","Come near to God and he will come near to you."),
("John 15:5","I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit."),
("Hebrews 11:1","Now faith is confidence in what we hope for and assurance about what we do not see."),
("Philippians 4:7","The peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus."),
("1 Thessalonians 5:18","Give thanks in all circumstances; for this is God's will for you in Christ Jesus."),
("Isaiah 40:28-29","The Lord is the everlasting God, the Creator of the ends of the earth. He will not grow tired or weary. He gives strength to the weary."),
("2 Timothy 1:7","For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline."),
("Romans 8:1","There is now no condemnation for those who are in Christ Jesus."),
("1 Corinthians 10:13","God is faithful; he will not let you be tempted beyond what you can bear."),
("Ephesians 4:32","Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you."),
("Proverbs 17:17","A friend loves at all times, and a brother is born for a time of adversity."),
("John 3:17","For God did not send his Son into the world to condemn the world, but to save the world through him."),
("Matthew 5:9","Blessed are the peacemakers, for they will be called children of God."),
("John 15:13","Greater love has no one than this: to lay down one's life for one's friends."),
("Hebrews 4:16","Let us then approach God's throne of grace with confidence, so that we may receive mercy and find grace."),
("Romans 6:23","For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord."),
("Matthew 28:19","Go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit."),
("Psalm 51:10","Create in me a pure heart, O God, and renew a steadfast spirit within me."),
("2 Corinthians 12:9","My grace is sufficient for you, for my power is made perfect in weakness."),
("Psalm 34:18","The Lord is close to the brokenhearted and saves those who are crushed in spirit."),
("Romans 12:12","Be joyful in hope, patient in affliction, faithful in prayer."),
("1 Peter 2:9","You are a chosen people, a royal priesthood, a holy nation, God's special possession."),
("Philippians 1:6","He who began a good work in you will carry it on to completion until the day of Christ Jesus."),
("Romans 8:31","If God is for us, who can be against us?"),
("John 6:35","I am the bread of life. Whoever comes to me will never go hungry, and whoever believes in me will never be thirsty."),
("Hebrews 12:1","Let us run with perseverance the race marked out for us."),
("1 John 1:9","If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness."),
("Matthew 5:6","Blessed are those who hunger and thirst for righteousness, for they will be filled."),
("Ephesians 6:10","Be strong in the Lord and in his mighty power."),
("Isaiah 60:1","Arise, shine, for your light has come, and the glory of the Lord rises upon you."),
("Romans 12:21","Do not be overcome by evil, but overcome evil with good."),
("James 5:16","The prayer of a righteous person is powerful and effective."),
("Proverbs 11:25","A generous person will prosper; whoever refreshes others will be refreshed."),
("1 Peter 3:15","Always be prepared to give an answer to everyone who asks you to give the reason for the hope that you have."),
("John 16:33","In this world you will have trouble. But take heart! I have overcome the world."),
("Luke 1:37","For no word from God will ever fail."),
("Psalm 139:14","I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well."),
("John 4:24","God is spirit, and his worshipers must worship in the Spirit and in truth."),
("Proverbs 16:9","In their hearts humans plan their course, but the Lord establishes their steps."),
("Isaiah 30:21","Whether you turn to the right or to the left, your ears will hear a voice behind you, saying, This is the way; walk in it."),
("Matthew 5:7","Blessed are the merciful, for they will be shown mercy."),
("Romans 12:10","Be devoted to one another in love. Honor one another above yourselves."),
("Hebrews 13:8","Jesus Christ is the same yesterday and today and forever."),
("Psalm 32:8","I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you."),
("John 15:7","If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you."),
("Proverbs 19:21","Many are the plans in a person's heart, but it is the Lord's purpose that prevails."),
("Isaiah 43:19","See, I am doing a new thing! Now it springs up; do you not perceive it?"),
("1 Corinthians 2:9","No eye has seen, no ear has heard, and no human mind has conceived the things God has prepared for those who love him."),
("Ephesians 1:7","In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace."),
("Romans 1:16","I am not ashamed of the gospel, because it is the power of God that brings salvation to everyone who believes."),
("Proverbs 24:16","For though the righteous fall seven times, they rise again, but the wicked stumble when calamity strikes."),
("Jeremiah 31:3","I have loved you with an everlasting love; I have drawn you with unfailing kindness."),
("1 Timothy 4:12","Don't let anyone look down on you because you are young, but set an example for the believers in speech, in conduct, in love, in faith and in purity."),
("Matthew 5:8","Blessed are the pure in heart, for they will see God."),
("Romans 5:1","Since we have been justified through faith, we have peace with God through our Lord Jesus Christ."),
("Isaiah 40:8","The grass withers and the flowers fall, but the word of our God endures forever."),
("John 1:1","In the beginning was the Word, and the Word was with God, and the Word was God."),
("Galatians 5:22-23","The fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control."),
("Hebrews 10:23","Let us hold unswervingly to the hope we profess, for he who promised is faithful."),
("Revelation 3:20","Here I am! I stand at the door and knock. If anyone hears my voice and opens the door, I will come in."),
("Psalm 103:2-3","Praise the Lord, my soul, and forget not all his benefits - who forgives all your sins and heals all your diseases."),
("1 Peter 4:8","Above all, love each other deeply, because love covers over a multitude of sins."),
("Psalm 23:4","Even though I walk through the darkest valley, I will fear no evil, for you are with me; your rod and your staff, they comfort me."),
("John 14:1","Do not let your hearts be troubled. You believe in God; believe also in me."),
("Romans 12:1","Offer your bodies as a living sacrifice, holy and pleasing to God - this is your true and proper worship."),
("1 Corinthians 13:13","And now these three remain: faith, hope and love. But the greatest of these is love."),
("Matthew 5:5","Blessed are the meek, for they will inherit the earth."),
("Ephesians 2:10","We are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do."),
("John 10:27","My sheep listen to my voice; I know them, and they follow me."),
("Romans 12:15","Rejoice with those who rejoice; mourn with those who mourn."),
("Psalm 31:24","Be strong and take heart, all you who hope in the Lord."),
("2 Timothy 3:16-17","All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness."),
("Hebrews 13:5","Never will I leave you; never will I forsake you."),
("Colossians 3:2","Set your minds on things above, not on earthly things."),
("Matthew 6:14","For if you forgive other people when they sin against you, your heavenly Father will also forgive you."),
("1 John 3:1","See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!"),
("Psalm 27:14","Wait for the Lord; be strong and take heart and wait for the Lord."),
("Isaiah 58:11","The Lord will guide you always; he will satisfy your needs in a sun-scorched land."),
("Hebrews 11:6","Without faith it is impossible to please God, because anyone who comes to him must believe that he exists."),
("Colossians 3:17","Whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him."),
("Psalm 46:10","Be still, and know that I am God; I will be exalted among the nations."),
("John 8:36","So if the Son sets you free, you will be free indeed."),
("Psalm 118:24","This is the day that the Lord has made; let us rejoice and be glad in it."),
("Matthew 5:10","Blessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven."),
("Romans 8:37","In all these things we are more than conquerors through him who loved us."),
("Isaiah 54:10","Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken."),
("John 5:24","Whoever hears my word and believes him who sent me has eternal life and will not be judged."),
("Acts 2:38","Repent and be baptized, every one of you, in the name of Jesus Christ for the forgiveness of your sins."),
("Romans 12:6","We have different gifts, according to the grace given to each of us."),
("1 John 4:8","Whoever does not love does not know God, because God is love."),
("Isaiah 55:11","So is my word that goes out from my mouth: It will not return to me empty, but will accomplish what I desire."),
("Hebrews 12:2","Fixing our eyes on Jesus, the pioneer and perfecter of faith."),
("John 3:30","He must become greater; I must become less."),
("1 Corinthians 6:19-20","Your bodies are temples of the Holy Spirit. You are not your own; you were bought at a price."),
("Jeremiah 33:3","Call to me and I will answer you and tell you great and unsearchable things you do not know."),
("Isaiah 64:8","Yet you, Lord, are our Father. We are the clay, you are the potter; we are all the work of your hand."),
("John 1:12","Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God."),
("2 Thessalonians 3:3","The Lord is faithful, and he will strengthen you and protect you from the evil one."),
("Luke 15:10","There is rejoicing in the presence of the angels of God over one sinner who repents."),
("Romans 5:3-4","We also glory in our sufferings, because suffering produces perseverance; perseverance, character; and character, hope."),
("Isaiah 26:4","Trust in the Lord forever, for the Lord, the Lord himself, is the Rock eternal."),
("Matthew 23:11","The greatest among you will be your servant."),
("John 9:5","While I am in the world, I am the light of the world."),
("Hebrews 4:12","The word of God is alive and active. Sharper than any double-edged sword."),
("1 John 5:14","This is the confidence we have in approaching God: that if we ask anything according to his will, he hears us."),
("Isaiah 41:13","For I am the Lord your God who takes hold of your right hand and says to you, Do not fear; I will help you."),
("Psalm 48:14","For this God is our God for ever and ever; he will be our guide even to the end."),
("Romans 8:14","For those who are led by the Spirit of God are the children of God."),
("Matthew 7:12","In everything, do to others what you would have them do to you."),
("Psalm 40:8","I desire to do your will, my God; your law is within my heart."),
("1 Corinthians 12:27","Now you are the body of Christ, and each one of you is a part of it."),
("Acts 16:31","Believe in the Lord Jesus, and you will be saved - you and your household."),
("Revelation 22:13","I am the Alpha and the Omega, the First and the Last, the Beginning and the End."),
("Hebrews 2:18","Because he himself suffered when he was tempted, he is able to help those who are being tempted."),
("Psalm 31:15","My times are in your hands."),
("Matthew 19:14","Let the little children come to me, and do not hinder them, for the kingdom of heaven belongs to such as these."),
("Isaiah 43:1","Do not fear, for I have redeemed you; I have summoned you by name; you are mine."),
("Colossians 3:14","Over all these virtues put on love, which binds them all together in perfect unity."),
("1 Samuel 16:7","People look at the outward appearance, but the Lord looks at the heart."),
("John 6:47","Very truly I tell you, the one who believes has eternal life."),
("Ephesians 4:29","Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up."),
("Psalm 145:3","Great is the Lord and most worthy of praise; his greatness no one can fathom."),
("Isaiah 48:17","I am the Lord your God, who teaches you what is best for you, who directs you in the way you should go."),
("Romans 8:18","I consider that our present sufferings are not worth comparing with the glory that will be revealed in us."),
("1 Corinthians 13:7","Love bears all things, believes all things, hopes all things, endures all things."),
("Hebrews 10:36","You need to persevere so that when you have done the will of God, you will receive what he has promised."),
("Philippians 4:11","I have learned to be content whatever the circumstances."),
("Romans 10:17","Faith comes from hearing the message, and the message is heard through the word about Christ."),
("Revelation 1:8","I am the Alpha and the Omega, says the Lord God, who is, and who was, and who is to come, the Almighty."),
("Matthew 21:22","If you believe, you will receive whatever you ask for in prayer."),
("Psalm 139:1-2","You have searched me, Lord, and you know me. You know when I sit and when I rise; you perceive my thoughts from afar."),
("Proverbs 16:20","Whoever gives heed to instruction prospers, and blessed is the one who trusts in the Lord."),
("Colossians 4:6","Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone."),
("Romans 15:5","May the God who gives endurance and encouragement give you the same attitude of mind toward each other that Christ Jesus had."),
("Matthew 11:30","For my yoke is easy and my burden is light."),
("1 John 4:4","You, dear children, are from God and have overcome them, because the one who is in you is greater than the one who is in the world."),
("Isaiah 40:11","He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart."),
("Romans 12:18","If it is possible, as far as it depends on you, live at peace with everyone."),
("Colossians 2:10","In Christ you have been brought to fullness. He is the head over every power and authority."),
("John 10:28","I give them eternal life, and they shall never perish; no one will snatch them out of my hand."),
("Galatians 2:20","I have been crucified with Christ and I no longer live, but Christ lives in me."),
("Matthew 25:40","Truly I tell you, whatever you did for one of the least of these brothers and sisters of mine, you did for me."),
("Romans 12:13","Share with the Lord's people who are in need. Practice hospitality."),
("Psalm 32:1","Blessed is the one whose transgressions are forgiven, whose sins are covered."),
("1 Corinthians 1:30","It is because of him that you are in Christ Jesus, who has become for us wisdom from God - our righteousness, holiness and redemption."),
("Proverbs 3:27","Do not withhold good from those to whom it is due, when it is in your power to act."),
("Hebrews 6:19","We have this hope as an anchor for the soul, firm and secure."),
("2 Corinthians 3:17","Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom."),
("Colossians 3:15","Let the peace of Christ rule in your hearts, since as members of one body you were called to peace."),
("Psalm 63:3","Because your love is better than life, my lips will glorify you."),
("Acts 4:12","Salvation is found in no one else, for there is no other name under heaven given to mankind by which we must be saved."),
("Proverbs 16:24","Gracious words are a honeycomb, sweet to the soul and healing to the bones."),
("James 1:22","Do not merely listen to the word, and so deceive yourselves. Do what it says."),
("Psalm 86:5","You, Lord, are forgiving and good, abounding in love to all who call to you."),
("2 Corinthians 4:17","For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all."),
("Proverbs 1:7","The fear of the Lord is the beginning of knowledge, but fools despise wisdom and instruction."),
("Romans 13:10","Love does no harm to a neighbor. Therefore love is the fulfillment of the law."),
("John 15:9","As the Father has loved me, so have I loved you. Now remain in my love."),
("Psalm 128:1","Blessed are all who fear the Lord, who walk in obedience to him."),
("Galatians 3:28","There is neither Jew nor Gentile, neither slave nor free, for you are all one in Christ Jesus."),
("Psalm 9:1","I will give thanks to you, Lord, with all my heart; I will tell of all your wonderful deeds."),
("Isaiah 25:8","He will swallow up death forever. The Sovereign Lord will wipe away the tears from all faces."),
("Colossians 1:27","Christ in you, the hope of glory."),
("Psalm 19:1","The heavens declare the glory of God; the skies proclaim the work of his hands."),
("1 Corinthians 13:7b","Love never fails. But where there are prophecies, they will cease; where there are tongues, they will be stilled."),
("Proverbs 15:15","All the days of the oppressed are wretched, but the cheerful heart has a continual feast."),
("Psalm 133:1","How good and pleasant it is when God's people live together in unity!"),
("Matthew 6:21","For where your treasure is, there your heart will be also."),
("1 Corinthians 3:16","Do you not know that you yourselves are God's temple and that God's Spirit dwells in your midst?"),
("Psalm 23:6","Surely your goodness and love will follow me all the days of my life, and I will dwell in the house of the Lord forever."),
("Romans 3:23-24","For all have sinned and fall short of the glory of God, and all are justified freely by his grace through the redemption that came by Christ Jesus."),
("John 15:16","You did not choose me, but I chose you and appointed you so that you might go and bear fruit."),
("Isaiah 9:6","For to us a child is born, to us a son is given, and he will be called Wonderful Counselor, Mighty God, Everlasting Father, Prince of Peace."),
("Psalm 50:15","Call on me in the day of trouble; I will deliver you, and you will honor me."),
("Romans 12:20","If your enemy is hungry, feed him; if he is thirsty, give him something to drink."),
("Psalm 86:11","Teach me your way, Lord, that I may rely on your faithfulness; give me an undivided heart."),
("Matthew 6:6","When you pray, go into your room, close the door and pray to your Father, who is unseen."),
("Proverbs 3:11-12","Do not despise the Lord's discipline, because the Lord disciplines those he loves."),
("Isaiah 61:1","The Spirit of the Sovereign Lord is on me, because the Lord has anointed me to proclaim good news to the poor."),
("Psalm 103:12","As far as the east is from the west, so far has he removed our transgressions from us."),
("Proverbs 15:1","A gentle answer turns away wrath, but a harsh word stirs up anger."),
("Luke 6:38","Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap."),
("Psalm 145:8","The Lord is gracious and compassionate, slow to anger and rich in love."),
("1 Peter 1:3","Praise be to the God and Father of our Lord Jesus Christ! In his great mercy he has given us new birth into a living hope through the resurrection of Jesus Christ."),
("Proverbs 20:7","The righteous lead blameless lives; blessed are their children after them."),
("Colossians 3:20","Children, obey your parents in everything, for this pleases the Lord."),
("Psalm 37:7","Be still before the Lord and wait patiently for him."),
("Isaiah 45:22","Turn to me and be saved, all you ends of the earth; for I am God, and there is no other."),
("Luke 6:31","Do to others as you would have them do to you."),
("1 Peter 5:6","Humble yourselves, therefore, under God's mighty hand, that he may lift you up in due time."),
("John 20:29","Blessed are those who have not seen and yet have believed."),
("Psalm 37:23-24","The Lord makes firm the steps of the one who delights in him; though he may stumble, he will not fall, for the Lord upholds him with his hand."),
("2 Corinthians 9:8","God is able to bless you abundantly, so that in all things at all times, you will abound in every good work."),
("Psalm 56:3-4","When I am afraid, I put my trust in you. In God I trust and am not afraid."),
("Proverbs 11:2","When pride comes, then comes disgrace, but with humility comes wisdom."),
("Colossians 3:12","Clothe yourselves with compassion, kindness, humility, gentleness and patience."),
("Psalm 25:4-5","Show me your ways, Lord, teach me your paths. Guide me in your truth and teach me, for you are God my Savior."),
("John 14:21","Whoever has my commands and keeps them is the one who loves me. The one who loves me will be loved by my Father."),
("Romans 12:17","Do not repay anyone evil for evil. Be careful to do what is right in the eyes of everyone."),
("Ephesians 6:1","Children, obey your parents in the Lord, for this is right."),
("Psalm 25:9","He guides the humble in what is right and teaches them his way."),
("Luke 10:27","Love the Lord your God with all your heart and with all your soul and with all your strength and with all your mind; and Love your neighbor as yourself."),
("Proverbs 28:13","Whoever conceals their sins does not prosper, but the one who confesses and renounces them finds mercy."),
("Romans 8:15","The Spirit you received brought about your adoption to sonship. And by him we cry, Abba, Father."),
("Psalm 116:1-2","I love the Lord, for he heard my voice; he heard my cry for mercy."),
("1 John 2:1","If anybody does sin, we have an advocate with the Father - Jesus Christ, the Righteous One."),
("Proverbs 30:5","Every word of God is flawless; he is a shield to those who take refuge in him."),
("Psalm 107:8-9","Let them give thanks to the Lord for his unfailing love, for he satisfies the thirsty and fills the hungry with good things."),
("Proverbs 18:24","There is a friend who sticks closer than a brother."),
("Hebrews 11:3","By faith we understand that the universe was formed at God's command."),
("Psalm 37:34","Hope in the Lord and keep his way. He will exalt you to inherit the land."),
("Matthew 18:3","Unless you change and become like little children, you will never enter the kingdom of heaven."),
("Proverbs 13:20","Walk with the wise and become wise, for a companion of fools suffers harm."),
("Romans 12:16","Live in harmony with one another. Do not be proud, but be willing to associate with people of low position."),
("Psalm 40:1-2","I waited patiently for the Lord; he turned to me and heard my cry. He lifted me out of the slimy pit."),
("John 11:35","Jesus wept."),
("Psalm 19:14","May these words of my mouth and this meditation of my heart be pleasing in your sight, Lord, my Rock and my Redeemer."),
("2 Corinthians 1:3-4","Praise be to the Father of compassion and the God of all comfort, who comforts us in all our troubles."),
("Matthew 7:11","How much more will your Father in heaven give good gifts to those who ask him!"),
("Luke 11:28","Blessed rather are those who hear the word of God and obey it."),
("Romans 13:8","Let no debt remain outstanding, except the continuing debt to love one another."),
("Psalm 139:23-24","Search me, God, and know my heart; test me and know my anxious thoughts. Lead me in the way everlasting."),
("James 3:17","The wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive, full of mercy and good fruit."),
("Psalm 57:1","Have mercy on me, my God, have mercy on me, for in you I take refuge."),
("Ephesians 5:1-2","Follow God's example, as dearly loved children and walk in the way of love."),
("Psalm 130:7","Put your hope in the Lord, for with the Lord is unfailing love and with him is full redemption."),
("Isaiah 57:15","I live in a high and holy place, but also with the one who is contrite and lowly in spirit."),
("Psalm 25:14","The Lord confides in those who fear him; he makes his covenant known to them."),
("John 14:23","Anyone who loves me will obey my teaching. My Father will love them, and we will come to them and make our home with them."),
("Proverbs 12:18","The words of the reckless pierce like swords, but the tongue of the wise brings healing."),
("Psalm 103:17","From everlasting to everlasting the Lord's love is with those who fear him."),
("Matthew 5:4","Blessed are those who mourn, for they will be comforted."),
("Colossians 1:13-14","He has rescued us from the dominion of darkness and brought us into the kingdom of the Son he loves."),
("John 7:37-38","Let anyone who is thirsty come to me and drink. Whoever believes in me, rivers of living water will flow from within them."),
("Psalm 73:26","My flesh and my heart may fail, but God is the strength of my heart and my portion forever."),
("2 Peter 3:9","The Lord is patient with you, not wanting anyone to perish, but everyone to come to repentance."),
("Proverbs 3:9-10","Honor the Lord with your wealth, with the firstfruits of all your crops; then your barns will be filled to overflowing."),
("Psalm 84:11","The Lord God is a sun and shield; he bestows favor and honor; no good thing does he withhold from those whose walk is blameless."),
("Romans 12:3","Do not think of yourself more highly than you ought, but rather think of yourself with sober judgment."),
("Matthew 6:34","Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own."),
("Psalm 86:15","But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness."),
("John 3:36","Whoever believes in the Son has eternal life, but whoever rejects the Son will not see life."),
("Proverbs 10:12","Hatred stirs up conflict, but love covers over all wrongs."),
("Isaiah 12:2","Surely God is my salvation; I will trust and not be afraid. The Lord, the Lord himself, is my strength and my defense."),
("Romans 4:20-21","Abraham did not waver through unbelief regarding the promise of God, but was strengthened in his faith and gave glory to God."),
("Colossians 3:13","Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you."),
("Psalm 62:1-2","Truly my soul finds rest in God; my salvation comes from him. Truly he is my rock and my salvation; he is my fortress."),
("John 17:3","Now this is eternal life: that they know you, the only true God, and Jesus Christ, whom you have sent."),
("Proverbs 14:26","Whoever fears the Lord has a secure fortress, and for their children it will be a refuge."),
("Isaiah 33:22","The Lord is our judge, the Lord is our lawgiver, the Lord is our king; it is he who will save us."),
("Romans 16:20","The God of peace will soon crush Satan under your feet."),
("Psalm 145:18","The Lord is near to all who call on him, to all who call on him in truth."),
("Matthew 5:3","Blessed are the poor in spirit, for theirs is the kingdom of heaven."),
("Luke 12:7","Even the very hairs of your head are all numbered. Do not be afraid; you are worth more than many sparrows."),
("1 Corinthians 16:13","Be on your guard; stand firm in the faith; be courageous; be strong."),
("Psalm 4:8","In peace I will lie down and sleep, for you alone, Lord, make me dwell in safety."),
("Romans 15:4","For everything that was written in the past was written to teach us, so that through the endurance taught in the Scriptures we might have hope."),
("Ephesians 1:11","In him we were also chosen, having been predestined according to the plan of him who works out everything in conformity with the purpose of his will."),
("John 7:17","Anyone who chooses to do the will of God will find out whether my teaching comes from God or whether I speak on my own."),
("Psalm 27:1","The Lord is my light and my salvation - whom shall I fear? The Lord is the stronghold of my life."),
("1 Peter 1:23","For you have been born again, not of perishable seed, but of imperishable, through the living and enduring word of God."),
("Romans 8:26","The Spirit helps us in our weakness. The Spirit himself intercedes for us through wordless groans."),
("Proverbs 31:25","She is clothed with strength and dignity; she can laugh at the days to come."),
("Psalm 16:8","I keep my eyes always on the Lord. With him at my right hand, I will not be shaken."),
("Matthew 22:37-38","Love the Lord your God with all your heart and with all your soul and with all your mind. This is the first and greatest commandment."),
]
print(f'Total: {len(verses)}')
with open('index.html','r',encoding='utf-8') as f: c=f.read()
lines=[]
for ref,text in verses:
    t=text.replace("'","\\'")
    lines.append(f"    {{text:'{t}',ref:'{ref}'}},")
new_arr="  const VERSES = [\n"+"\n".join(lines)+"\n  ];"
import re
c2=re.sub(r'const VERSES = \[.*?\];',new_arr,c,flags=re.DOTALL)
with open('index.html','w',encoding='utf-8') as f: f.write(c2)
print('Done - updated index.html')
